<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8" />
	<link rel='shortcut icon' type='image/x-icon' href='favicon.ico' />
	<title>Order Records</title>
</head>
<body>

<?php
/* This code dynamically generates a web page containing a form designed with the html required to display one
checkbox for each of the records currently held in the nmc_records database table has been provided for you in the
assessment section for the module on blackboard. The user can select one or more records that they are interested in
ordering by clicking the checkboxes.
Use the browser to look at the structure of the html generated by the php code. */

$url = "http://unn-izge1.newnumyspace.co.uk/KF5002/assessment/orderRecordsFormInc.php";
$curl = curl_init($url);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
$result = curl_exec($curl);
curl_close($curl);
echo $result;
?>

<script type="text/javascript">



	window.addEventListener('load',function()
	{
		'use strict';
		var hasNames = false;
		var hasCompanyName = false;
		var orderCount = 0;

		const termsText = document.getElementById('termsText');
		const checkbox = termsText.querySelector("input[name='termsChkbx']");
		const submit = document.querySelector("input[name='submit']");

		const form_checkbox = document.getElementById('selectRecords').getElementsByTagName("input");

		const names = document.getElementById('retCustDetails');
		const companyName = document.getElementById('tradeCustDetails');
		const f_name = document.querySelector("input[name='forename']");
		const l_name = document.querySelector("input[name='surname']");
		const company = document.querySelector("input[name='companyName']");

		for (var i = 0; i < form_checkbox.length; i++){
			if (form_checkbox[i].type === "checkbox"){
				form_checkbox[i].addEventListener("change",function(){
					if(this.checked === true) {
						orderCount++;
					}
					else {
						orderCount--;
					}
				});
			}
		}

		names.addEventListener("change",function(){
			if (f_name.value.length != 0 && l_name.value.length != 0){
				hasNames = true;
			}
			else {
				hasNames = false;
			}
		});

		checkbox.onchange = function canSubmit(){
			if (checkbox.checked)
			{
				termsText.style.color='black';
				termsText.style.fontWeight = 'normal';
				if (hasNames == true && orderCount != 0){
					submit.disabled = false;
				}
				else {
					submit.diabled = true;
				}
			}
			else {
				termsText.style.color = 'red';
				termsText.style.fontWeight = 'bold';
				//submit.disabled = true;
			}
		};

	});


</script>

</body>
</html>
